### ISSUE TITLE
Liste regioner uten aktive meetups

### ISSUE THREAD

**Issue by Espenhh** [javaBin/javabin.github.com#16]
Hadde vært fint om regioner som ikke har en aktiv fremtidig meetup ikke bare skjules fra meetup-listen, men heller listes med en tekst som sier dette. F.eks "Ingen fremtidige meetups er planlagt enda. Hva med å foreslå en på meetup.com/<region>"

**Comment by mehmandarov** [comment]
+1. Dette kunne ha vært fint å få på plass.
