### ISSUE TITLE
Gjøre meetup-integrasjon https-kompatibel

### ISSUE THREAD

**Issue by henrikno** [javaBin/javabin.github.com#17]
Meetup-urlen som brukes i dag
```http://api.meetup.com/2/events?group_id=7480032%2C8449272%2C7371452%2C4060032%2C10847532%2C1764379&status=upcoming&order=time&limited_events=False&desc=false&offset=0&format=json&page=20&fields=&sig_id=14499833&sig=5cd7131eecfb2f8b4581762dd8c58c77c266d23d"```
er ikke https, så https://java.no/ laster ikke meetups. Lenken er generert av meetup, tror noen må logge inn på meetup og generere en ny.

**Comment by mehmandarov** [comment]
Ser ut som det funker nå. Både med http og https. Lukker saken.
