### ISSUE TITLE
Slå sammen "Neste meetups" og "Regioner"

### ISSUE THREAD

**Issue by stolsvik** [javaBin/javabin.github.com#39]
Jeg tror det hadde vært lurt å bare slå sammen avsnittene "Neste meetups" og "Regioner" til ett avsnitt.
Hvis man tok de to linjene som står under hver region under avsnittet "Regioner", og puttet disse to linjene inn under regionsnavnet under avsnittet "Neste meetups", så hadde man hatt alt på ett brett.
Da kunne det resulterende avsnittet bli kalt **"Neste Meetups / javaBin Regioner"**.

Jeg tror det både ville bli mer kompakt, mer informativt og mer logisk.

De to linkene på toppen ("menyen") kunne pekt til samme anchor.

**Comment by dervism** [comment]
Fixed in #45
